### ISSUE TITLE
:path no longer a valid key for build options

### ISSUE THREAD

**Issue by svard** [jalehman/omtut-starter#2]
In the latest version of the om library code like this no longer work since :path is not a valid key

``` clojure
(map #(om/build comment app
                             {:path [:comments %]
                              :key :id})
                  (range (count (:comments app))))
```

I'm not sure if the :opts or :fn keys should be used to get the individual maps from the comments vector or what the correct way is?

**Comment by jalehman** [comment]
This is now fixed -- there were a number of breaking changes in the API. I've revamped the walkthroughs and code to reflect changes up to Om 0.1.4.

**Comment by svard** [comment]
Thanks for your work. The tutorial is really helpful!

**Comment by jalehman** [comment]
Glad to hear!
