### ISSUE TITLE
 No protocol method IRender.render defined for type omtut.core/t15209: [object Object] 

### ISSUE THREAD

**Issue by geodrome** [jalehman/omtut-starter#3]
When I follow getting started instructions in README.md I get the following error in the console:

Uncaught Error: No protocol method IRender.render defined for type omtut.core/t15209: [object Object] 

Tried it twice and made sure the project actually compiled. Going to try to figure it out, but thought I would post this. The error can be traced to this line:

(om/root app-state omtut-app (.getElementById js/document "content"))

**Comment by jalehman** [comment]
This is now fixed -- there were a number of breaking changes in the API. I've revamped the walkthroughs and code to reflect changes up to Om 0.1.4.
