### ISSUE TITLE
Typo in source files

### ISSUE THREAD

**Issue by chrisuehlinger** [jalehman/omtut-starter#8]
First off, thanks a bunch for making this tutorial!

I was having a bit of trouble at one point, and tried to use the code from the repo while I figured out where the problem was. I kept getting errors in the console until I changed the following bit of code.

In the code in the repo, the call to `om/root` is written like this:

`(om/root app-state omtut-starter-app (.getElementById js/document "content"))`

when it should be:

`(om/root omtut-starter-app app-state {:target (.getElementById js/document "content")} )`

Also, when I run the code in the tutorial8 branch, It renders as:
# Comments

032374988
Hello, world! I am a CommentForm.

Still trying to figure out what's going on there.

**Comment by jalehman** [comment]
Om changed quite a bit since I originally wrote the walkthrough. Just went through and updated all of the branches. Thanks!
